### ISSUE TITLE
Окна контейнеров

### ISSUE THREAD

**Issue by chiruno** [TatriX/rogalik#10]
Сделай так, чтобы положение окна для каждого типа контейнеров было одним и тем же. Ну то есть например я открыл деревянный сундук А, перетащил окно в правый нижний угол, потом пошел к деревянному сундуку "Б", и окно открылось в правом нижнем углу.(уиии, я пользуюсь гитхабом, я теперь настоящий хакер!!)

**Comment by TatriX** [comment]
Closed by c4d18140e2c717271a72f9f2e9589657c48b8eeb
