### ISSUE TITLE
Конфликт имён в сырцах: Umi.png & umi.png

### ISSUE THREAD

**Issue by MarisaLovesUsAll** [TatriX/rogalik#23]
NTFS считает одинаковыми вот эти два файла:

assets/characters/Umi.png
assets/characters/umi.png

Ей плевать на регистр букв в названии, в отличие от линупсовых ext3/ext4.
Потому что она может.

**Comment by TatriX** [comment]
Удалил Umi.png. Этот файл больше не нужен. 6beabcd14ba0a4839d988461e4cd6641c9bf90ac
